#!/usr/bin/python3
# -*- coding: utf-8 -*-
from utils.argparsing import Pattern
from utils.yamlfile import YamlFile
from core.daemonctl import DaemonCtl
from core.daemon import Daemon
from sys import argv as sys_argv

if __name__ == '__main__':

    """Daemon test logic.

    This logic must be called as seperate executable (i.e. python3
    daemon.py start/stop/restart).

    See test_daemon.py for implementation.

    usage = 'Missing parameter, usage of test logic:\n' + \
            ' % python3 daemon.py start|restart|stop\n'
    """

    usage = [
        'start',
        'stop',
        'restart'
    ]

    pattern = Pattern(usage)
    user_command = pattern.compare_with(sys_argv)

    # load configuration
    configuration = YamlFile.read('config/sledge-config.yml')
    pidfile = configuration['pidfile']

    dc = DaemonCtl(Daemon, pidfile)

    if user_command.get('start'):
        dc.start()
    elif user_command.get('stop'):
        dc.stop()
    elif user_command.get('restart'):
        dc.restart()
