#!/usr/bin/python3
# -*- coding: utf-8 -*-
from core.daemonctl import DaemonCtl
from core.server import SocketServer
from sys import argv as sys_argv
import argparse

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description= 'Sledge daemon')

    parser.add_argument('command',
                        choices=['start', 'stop', 'restart'],
                        action='store',
                        help="start|stop|restart the daemon")

    parser.add_argument('-v', '--verbose',
                        help='increase output verbosity',
                        action='count',
                        default=0)

    args = parser.parse_args()

    # manage daemon
    dc = DaemonCtl(SocketServer)

    if args.command == 'start':
        dc.start()
    elif args.command == 'stop':
        dc.stop()
    elif args.command == 'restart':
        dc.restart()
